import type { Metadata } from "next";

import { cn } from "@shared/utils/cn";

import { Providers } from "./_lib/Providers";
import { font } from "./_lib/font";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen overflow-x-hidden bg-background font-sans antialiased",
          font.variable
        )}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
